### ISSUE TITLE
Improvements in Slots?

### ISSUE THREAD

**Issue by Xaikii** [TheRActivator/From-the-Ground-Up#40]
Hey,

I found your Mod and actually pretty liked it and using it currently in my Modpack.
At the Moment I didn't really figure out how the "late-game technology", but from that what I've seen and tested already I have to say I feel a bit restricted by the slots avaible in Idea Table and Research Table.
E.g. A Data Chip
In a Research Table.
Currently you'd be able to set 3x3 where it could be like that:

< iron>, < iron>, < iron>
< iron>, < redstone>, < iron>
< iron>, < iron>, < iron>

Tbh if you someone would like to create a bit harder realism that's pretty uncreative.
Meanwhile already with a 5x5 (maybe up to 9x9(Extreme Crafting), or even further beyond) you could make it more realistic like fit the texture to the recipe or even a real setup of (e.g.)a Data Chip.

I noticed that pretty much when I tried using adding custom ones.
Also with the Idea Table I think even 3 Slots are simply not enough, but unlike the Research Table I think the Idea Table would be with 9 Slots absolutely fine!

Another Feature I think would be usefull, is the Recipe Showing from JEI. So basically currently if an item is uncraftable because you havent discovered it yet, it'll still show up the recipe, my idea would that it'll show what'll be required to unlock it and that you can go on the single requirements what you have to do there.

Also an Idea would be that you'd have to "study" or kill some mobs that you can learn some recipes.
Why? Basically Humanity had a lot cases where we got very good idea from animals how some things worked and realised them afterwards.

After all these Ideas I actually got a question because I am not sure, 
let's say you have discovered iron ingots yet, you can't obtain them, is it still possible to obtain them with Modded Machines? (e.g. Tinker's Construct Smeltery)
If yes, is there a way to remove that?

Greetings
- Xaikii

**Comment by Astavie** [comment]
Hey Xaikii,

I already have plans to rework FTGU a bit, to make less tedious and more realistic. That part where you mention "studying" is (sort of) a part of that :)

Secondly, I like the idea of a bigger research table, but I think that would be a new (and improved!) block. So you'd have the normal Research Table and a... Research Station? I'm not very good at names.

Anyways, machines are not and will never be restricted by FTGU. This is simply because machines output without a player clicking on an output slot, so FTGU can't possibly know for which player it should be locked.

To lock iron ingots you just have to lock seared bricks if your modpack includes Tinker's Construct.

**Comment by Xaikii** [comment]
Hehe nice to know :)

Yeah I thought also an improved version of the Block ^^ 
Who is good at names?xD

Is there really no way to prevent it? :/ 
Would it be possible chosen Items not be able to pick it up out of machines or chest until you unlocked it? e.g. if you'd have stone age an then a revolution to machines, so you have to clear the stone age first to use/build the machines. Because you simply can't know what's a Railgun if you just met a Slingshot :D

**Comment by Astavie** [comment]
Well thats possible but then the player can just put a hopper under the machine to collect it
And locking items in hoppers based on where it's from is going a bit too far
