### ISSUE TITLE
[1.12.2] Crash upon trying to open the research book

### ISSUE THREAD

**Issue by NotAVerb** [TheRActivator/From-the-Ground-Up#44]
I just installed FTGU and have been unable to open the book the player spawns with.
I got this crash with only FTGU installed.
https://gist.github.com/NotAVerb/927e312d9672550d214442f83c87b786
V. b1.2.8
Forge 2611

**Comment by Josral** [comment]
Trying out your mod and had a crash when trying to open the research book you spawn with.  Thought it appropriate to put here rather than open a new issue for same topic.

[crash-2018-12-21_14.33.04-client.txt](https://github.com/Astavie/From-the-Ground-Up/files/2704040/crash-2018-12-21_14.33.04-client.txt)
