### ISSUE TITLE
I'm building the source to test the CraftTweaker integeration. If it works, may I...?

### ISSUE THREAD

**Issue by GazbonicAcid** [TheRActivator/From-the-Ground-Up#5]
I'm building the source to test the CraftTweaker integeration.
If it works and I don't experience any bugs, may I include it in my modpack?
I would ofcourse put in a warning that I built it from source and thus is a more prone to bugs and breaking/crashing.
But that's **if** it works for me _and_ I get the okay from you.

**Comment by Astavie** [comment]
It has been a month, hasn't it? I am currently releasing an experimental version that has the crafttweaker support in it. I am planning to start adding new features in the holidays, but I may be busy with other things, who knows.

**Comment by Astavie** [comment]
Also yes, this mod is free to use in any modpack _if you give me credit in some visible way (like linking to the curseforge page)_

**Comment by GazbonicAcid** [comment]
Thanks, Awesome!
Though I meant specifically the copy I built from source myself.
However since you're releasing your own build with the crafttweaker support in I won't need to.

**Comment by Astavie** [comment]
https://github.com/TheRActivator/From-the-Ground-Up/releases/tag/1.10.2-b1.1_pre1
Here is the pre-release for now, and this thread is closed!

**Comment by GazbonicAcid** [comment]
Will you be putting the crafttweaker support documentation up on the minetweaker wiki once the crafttweaker support is officially released?
As a matter of fact, I'm feeling some mild emotional discomfort at the thought of trial and erroring my way to figuring out how to do it from source.
Right when I got to the point of typing "...feeling some mild..." I made up my mind to do so anyway.
Doubly thinking to myself "f*** it, I'm doing it anyway."
Once for the trial and error experimentation,
and a second time for posting that statement anyway despite the "f*** it" on experimenting.
P.S. I posted the statement anyway because I feel it would be too dishonest, or too "sleazy", of me to simply cut it out of the conversation.

**Comment by Astavie** [comment]
Oh right, I should probably explain _how_ the crafttweaker support even works, and - even though you said yourself you like the idea of experimenting - I think I should probably tell you.
So there are 4 methods:

1. "mods.ftgu.Technology.addTechnology"
- String page: Since you can't make a new page yet, I recommend putting "Minecraft" here
- String prev: The name of the technology prior to the one you are making. Can be null
- String[] secret (optional): Names of other techs that are prerequisites
- IItemStack icon: An item that is shown as the icon of the tech
- boolean hide (optional): Hide this tech from the book until it is researched
- int x, int y, String name: Should be obvious
- IIngredient[] item: Modded items that are unlocked by researching this tech

For example: "mods.ftgu.Technology.addTechnology("Minecraft", null, \<minecraft:dye:0\>, 10, 5, "the_holy_ink_sac", [\<minecraft:dye:0\>,\<minecraft:wool:15\>]);"

2. "mods.ftgu.Idea.addIdea"
- String tech: The name of the tech you want to add a recipe to
- IIngredient[] item: A list of 1-3 items that make up your recipe

For example: "mods.ftgu.Idea.addIdea("the_holy_ink_sac", [\<minecraft:dye:0\>,\<minecraft:wool:15\>]);"

3. "mods.ftgu.Research.addResearch"
- String tech: The name of the tech
- IIngredient[][] item: A 3x3 grid of items, should be made like adding a crafting recipe with crafttweaker

For example: "mods.ftgu.Research.addResearch("the_holy_ink_sac", [[null, null, null],[null,\<minecraft:dye:0\>,null],[null,\<minecraft:wool:15\>,null]]);"

4. "mods.ftgu.Scramble.addScrambled"
- String tech: The name
- IIngredient ingredient: The block you need to look at to unscramble the hint
- int[] slots: The slots that are affected (from 0-8)

For example: "mods.ftgu.Scramble.addScrambled("the_holy_ink_sac", \<minecraft:wool:15\>, [4, 7]);"

**Comment by majix560** [comment]
Just to make sure I'm getting the first two right...
Technologies are how I make the researchable points,
and ideas are how I add recipe's to a technology?

**Comment by majix560** [comment]
> Also yes, this mod is free to use in any modpack if you give me credit in some visible way (like linking to the curseforge page)
Could you please add this to the curse/curseforge page?
